apiVersion: apps/v1
kind: Deployment
metadata:
  name: steamshine
  labels:
    app: steamshine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: steamshine
  template:
    metadata:
      labels:
        app: steamshine
    spec:
      containers:
        - name: steamshine
          image: ghcr.io/cmmmota/steamshine:latest
          imagePullPolicy: Always
          env:
            - name: DISPLAY_WIDTH
              value: "1920"
            - name: DISPLAY_HEIGHT
              value: "1080"
            - name: DISPLAY_REFRESH
              value: "60"
          # Security context for DRM access / input
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN", "SYS_NICE"]
          ports:
            - containerPort: 47984 # Sunshine TCP
            - containerPort: 47989 # Sunshine TCP
            - containerPort: 47990 # Sunshine Web UI
            - containerPort: 47998 # Sunshine UDP
            - containerPort: 47999 # Sunshine UDP
            - containerPort: 48000 # Sunshine UDP
            - containerPort: 48010 # Sunshine UDP
          resources:
            limits:
              amd.com/gpu: 1
              memory: "8Gi"
              cpu: "4"
            requests:
              amd.com/gpu: 1
              memory: "4Gi"
              cpu: "2"
          volumeMounts:
            - name: steam-data
              mountPath: /home/steamshine/.steam
            - name: sunshine-config
              mountPath: /home/steamshine/.config/sunshine
            - name: dshm
              mountPath: /dev/shm
            - name: uinput
              mountPath: /dev/uinput
      volumes:
        - name: steam-data
          persistentVolumeClaim:
            claimName: steam-data-pvc
        - name: sunshine-config
          persistentVolumeClaim:
            claimName: sunshine-config-pvc
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
        - name: uinput
          hostPath:
            path: /dev/uinput
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: steam-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sunshine-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: steamshine-web
spec:
  selector:
    app: steamshine
  ports:
    - protocol: TCP
      port: 47990
      targetPort: 47990
      name: web-ui
  type: LoadBalancer # Or ClusterIP/NodePort depending on your ingress
---
apiVersion: v1
kind: Service
metadata:
  name: steamshine-streaming
spec:
  selector:
    app: steamshine
  ports:
    - name: tcp-47984
      protocol: TCP
      port: 47984
      targetPort: 47984
    - name: tcp-47989
      protocol: TCP
      port: 47989
      targetPort: 47989
    - name: udp-47998
      protocol: UDP
      port: 47998
      targetPort: 47998
    - name: udp-47999
      protocol: UDP
      port: 47999
      targetPort: 47999
    - name: udp-48000
      protocol: UDP
      port: 48000
      targetPort: 48000
    - name: udp-48010
      protocol: UDP
      port: 48010
      targetPort: 48010
  type: NodePort # Usually streaming needs direct access or HostNetwork, NodePort is a safe start
